services:
  db:
    image: postgres:17
    ports: ["5432:5432"]
  
    env_file:
      - .env.dev
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    
    volumes:
      - dev_db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports: ["8080:80"]
    env_file:
      - .env.dev
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db

  backend:
    build: ..
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ../src:/opt/app/src
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db

volumes:
  dev_db: